// <auto-generated />
namespace Scandimex.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdPersonaContacto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdPersonaContacto));
        
        string IMigrationMetadata.Id
        {
            get { return "201705082123202_UpdPersonaContacto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
